//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAIUA.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WAIUA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONLY log into your Riot account if there are issues with the app or if Valorant is not running.
        /// </summary>
        public static string AccountExplanation {
            get {
                return ResourceManager.GetString("AccountExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in with either you Riot Account details or automatically log in if you have Valorant open. Ensure you have selected the correct region..
        /// </summary>
        public static string AccountInfoExplanation1 {
            get {
                return ResourceManager.GetString("AccountInfoExplanation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All communication regarding your credentials is done directly with Riot servers with no storage of passwords being done locally or online..
        /// </summary>
        public static string AccountInfoExplanation2 {
            get {
                return ResourceManager.GetString("AccountInfoExplanation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string AccountTitle {
            get {
                return ResourceManager.GetString("AccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia Pacific.
        /// </summary>
        public static string AP {
            get {
                return ResourceManager.GetString("AP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made By Soneliem.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticated as:.
        /// </summary>
        public static string AuthStatusAuthAs {
            get {
                return ResourceManager.GetString("AuthStatusAuthAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Authentication.
        /// </summary>
        public static string AuthStatusButton {
            get {
                return ResourceManager.GetString("AuthStatusButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click below to update.
        /// </summary>
        public static string AuthStatusDefault {
            get {
                return ResourceManager.GetString("AuthStatusDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Authenticated.
        /// </summary>
        public static string AuthStatusFail {
            get {
                return ResourceManager.GetString("AuthStatusFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Status.
        /// </summary>
        public static string AuthStatusTitle {
            get {
                return ResourceManager.GetString("AuthStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Valorant needs to be running for this to work.
        /// </summary>
        public static string AutoLoginExplanation {
            get {
                return ResourceManager.GetString("AutoLoginExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Login.
        /// </summary>
        public static string AutoLoginTitle {
            get {
                return ResourceManager.GetString("AutoLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazil.
        /// </summary>
        public static string BR {
            get {
                return ResourceManager.GetString("BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string CheckUpdates {
            get {
                return ResourceManager.GetString("CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version: .
        /// </summary>
        public static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe.
        /// </summary>
        public static string EU {
            get {
                return ResourceManager.GetString("EU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re on this page idiot.
        /// </summary>
        public static string InfoExplanation {
            get {
                return ResourceManager.GetString("InfoExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string InfoTitle {
            get {
                return ResourceManager.GetString("InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join my Discord.
        /// </summary>
        public static string JoinDiscord {
            get {
                return ResourceManager.GetString("JoinDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For support, etc..
        /// </summary>
        public static string JoinDiscordSub {
            get {
                return ResourceManager.GetString("JoinDiscordSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korea.
        /// </summary>
        public static string KO {
            get {
                return ResourceManager.GetString("KO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latin America.
        /// </summary>
        public static string LATAM {
            get {
                return ResourceManager.GetString("LATAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Version: .
        /// </summary>
        public static string Latestversion {
            get {
                return ResourceManager.GetString("Latestversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loads live match data if available. This should take less than 10 seconds.
        /// </summary>
        public static string LoadMatchExplanation {
            get {
                return ResourceManager.GetString("LoadMatchExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Match.
        /// </summary>
        public static string LoadMatchTitle {
            get {
                return ResourceManager.GetString("LoadMatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North America.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click To Refresh Match.
        /// </summary>
        public static string RefreshMatch {
            get {
                return ResourceManager.GetString("RefreshMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riot Login.
        /// </summary>
        public static string RiotLogin {
            get {
                return ResourceManager.GetString("RiotLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play around with each region if you are not sure which one you are in.
        /// </summary>
        public static string SelRegionExplanation {
            get {
                return ResourceManager.GetString("SelRegionExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Region.
        /// </summary>
        public static string SelRegionTitle {
            get {
                return ResourceManager.GetString("SelRegionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated into English By Soneliem.
        /// </summary>
        public static string Translator {
            get {
                return ResourceManager.GetString("Translator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who Am I Up Against?.
        /// </summary>
        public static string WAIUAFull {
            get {
                return ResourceManager.GetString("WAIUAFull", resourceCulture);
            }
        }
    }
}
