//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAIUA.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WAIUA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made By Soneliem.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticated as:.
        /// </summary>
        public static string AuthStatusAuthAs {
            get {
                return ResourceManager.GetString("AuthStatusAuthAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Authentication.
        /// </summary>
        public static string AuthStatusButton {
            get {
                return ResourceManager.GetString("AuthStatusButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click below to update.
        /// </summary>
        public static string AuthStatusDefault {
            get {
                return ResourceManager.GetString("AuthStatusDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Authenticated.
        /// </summary>
        public static string AuthStatusFail {
            get {
                return ResourceManager.GetString("AuthStatusFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Status.
        /// </summary>
        public static string AuthStatusTitle {
            get {
                return ResourceManager.GetString("AuthStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Valorant needs to be running for this to work.
        /// </summary>
        public static string AutoLoginExplanation {
            get {
                return ResourceManager.GetString("AutoLoginExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Login.
        /// </summary>
        public static string AutoLoginTitle {
            get {
                return ResourceManager.GetString("AutoLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Update.
        /// </summary>
        public static string CheckDownloadButton {
            get {
                return ResourceManager.GetString("CheckDownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Downloaded Content.
        /// </summary>
        public static string CheckDownloadTitle {
            get {
                return ResourceManager.GetString("CheckDownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string CheckUpdates {
            get {
                return ResourceManager.GetString("CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version: .
        /// </summary>
        public static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re on this page idiot.
        /// </summary>
        public static string InfoExplanation {
            get {
                return ResourceManager.GetString("InfoExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string InfoTitle {
            get {
                return ResourceManager.GetString("InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join my Discord.
        /// </summary>
        public static string JoinDiscord {
            get {
                return ResourceManager.GetString("JoinDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For support, etc..
        /// </summary>
        public static string JoinDiscordSub {
            get {
                return ResourceManager.GetString("JoinDiscordSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Version: .
        /// </summary>
        public static string Latestversion {
            get {
                return ResourceManager.GetString("Latestversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loads live match data if available. This should take less than 10 seconds.
        /// </summary>
        public static string LoadMatchExplanation {
            get {
                return ResourceManager.GetString("LoadMatchExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Match.
        /// </summary>
        public static string LoadMatchTitle {
            get {
                return ResourceManager.GetString("LoadMatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Match Detected.
        /// </summary>
        public static string NoMatch {
            get {
                return ResourceManager.GetString("NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Open Valorant First.
        /// </summary>
        public static string NoValGame {
            get {
                return ResourceManager.GetString("NoValGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing....
        /// </summary>
        public static string Refreshing {
            get {
                return ResourceManager.GetString("Refreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click To Refresh Match.
        /// </summary>
        public static string RefreshMatch {
            get {
                return ResourceManager.GetString("RefreshMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string SelLanguageTitle {
            get {
                return ResourceManager.GetString("SelLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find app and account settings here.
        /// </summary>
        public static string SettingsExplanation {
            get {
                return ResourceManager.GetString("SettingsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page lets you manually sign in, change the app language, etc..
        /// </summary>
        public static string SettingsInfoExplanation1 {
            get {
                return ResourceManager.GetString("SettingsInfoExplanation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All communication regarding your credentials is done directly with Riot servers with no storage of passwords being done locally or online..
        /// </summary>
        public static string SettingsInfoExplanation2 {
            get {
                return ResourceManager.GetString("SettingsInfoExplanation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported By:.
        /// </summary>
        public static string SupportedBy {
            get {
                return ResourceManager.GetString("SupportedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Tracker.gg Profile.
        /// </summary>
        public static string TrackerToolTip {
            get {
                return ResourceManager.GetString("TrackerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated into English By Soneliem.
        /// </summary>
        public static string Translator {
            get {
                return ResourceManager.GetString("Translator", resourceCulture);
            }
        }
    }
}
